DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS sellers CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS review_helpfuls CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;

ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS fk_users_provider;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS fk_users_condo;
ALTER TABLE IF EXISTS condominios DROP CONSTRAINT IF EXISTS fk_condo_sindico;
ALTER TABLE IF EXISTS providers DROP CONSTRAINT IF EXISTS fk_providers_owner;

DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS condominios CASCADE;
DROP TABLE IF EXISTS users CASCADE;
