"use client";
import { useEffect,useRef,useState } from "react";
import { adminApi,ApiBlogPost,BlogPostFormat } from "@/lib/api";
const empty={title:"",slug:"",excerpt:"",format:"traditional" as BlogPostFormat,content_html:"",published:false};
export function BlogSection(){
 const [posts,setPosts]=useState<ApiBlogPost[]>([]),[form,setForm]=useState(empty),[edit,setEdit]=useState<ApiBlogPost|null>(null),[busy,setBusy]=useState(false); const editor=useRef<HTMLDivElement>(null),cover=useRef<HTMLInputElement>(null),pdf=useRef<HTMLInputElement>(null),contentImage=useRef<HTMLInputElement>(null);
 const load=()=>adminApi.listBlogPosts().then(setPosts); useEffect(()=>{load()},[]);
 const slug=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
 const start=(p?:ApiBlogPost)=>{setEdit(p||null);setForm(p?{title:p.title,slug:p.slug,excerpt:p.excerpt,format:p.format,content_html:p.content_html,published:p.published}:empty);setTimeout(()=>{if(editor.current)editor.current.innerHTML=p?.content_html||""},0)};
 async function save(){setBusy(true);try{const payload={...form,content_html:editor.current?.innerHTML||form.content_html};const p=edit?await adminApi.updateBlogPost(edit.id,payload):await adminApi.createBlogPost(payload);const cf=cover.current?.files?.[0],pf=pdf.current?.files?.[0];if(cf)await adminApi.uploadBlogCover(p.id,cf);if(pf)await adminApi.uploadBlogPDF(p.id,pf);start();await load()}finally{setBusy(false)}}
 const cmd=(c:string,v?:string)=>{document.execCommand(c,false,v);editor.current?.focus()};
 async function insertImage(){const f=contentImage.current?.files?.[0];if(!f)return;const {url}=await adminApi.uploadBlogContentImage(f);cmd("insertImage",url);if(contentImage.current)contentImage.current.value=""}
 return <section><div className="admin-section-head"><div><h2 className="admin-section-title">Blog</h2><p className="admin-section-sub">Artigos e apresentações em PDF</p></div><button className="admin-primary-btn" onClick={()=>start()}>Nova postagem</button></div>
 <div className="admin-form-card"><div className="admin-form-title">{edit?"Editar":"Nova"} postagem</div><div className="prof-field"><label className="prof-label">Formato</label><select className="prof-input" value={form.format} onChange={e=>setForm({...form,format:e.target.value as BlogPostFormat})}><option value="traditional">Post tradicional</option><option value="presentation">Apresentação em PDF</option></select></div>
 <div className="prof-field"><label className="prof-label">Título</label><input className="prof-input" value={form.title} onChange={e=>setForm({...form,title:e.target.value,slug:edit?form.slug:slug(e.target.value)})}/></div><div className="prof-field"><label className="prof-label">Slug</label><input className="prof-input" value={form.slug} onChange={e=>setForm({...form,slug:slug(e.target.value)})}/></div><div className="prof-field"><label className="prof-label">Resumo</label><textarea className="prof-input" value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})}/></div><div className="prof-field"><label className="prof-label">Imagem de capa</label><input ref={cover} type="file" accept="image/*"/></div>
 {form.format==="presentation"?<div className="prof-field"><label className="prof-label">PDF da apresentação (máx. 20 MB)</label><input ref={pdf} type="file" accept="application/pdf"/></div>:<div className="prof-field"><label className="prof-label">Conteúdo</label><div style={{display:"flex",gap:8,marginBottom:8,flexWrap:"wrap"}}><button onClick={()=>cmd("bold")}><b>B</b></button><button onClick={()=>cmd("italic")}><i>I</i></button><button onClick={()=>cmd("formatBlock","h2")}>Título</button><button onClick={()=>cmd("insertUnorderedList")}>Lista</button><input ref={contentImage} type="file" accept="image/*" onChange={insertImage}/></div><div ref={editor} contentEditable className="prof-input" style={{minHeight:240,background:"white"}}/></div>}
 <label><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Publicado</label><button className="admin-primary-btn" disabled={busy||!form.title||!form.slug} onClick={save}>{busy?"Salvando…":"Salvar postagem"}</button></div>
 <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Título</th><th>Formato</th><th>Status</th><th></th></tr></thead><tbody>{posts.map(p=><tr key={p.id}><td>{p.title}</td><td>{p.format==="presentation"?"Apresentação":"Tradicional"}</td><td>{p.published?"Publicado":"Rascunho"}</td><td><button onClick={()=>start(p)}>Editar</button> <button onClick={async()=>{if(confirm("Excluir postagem?")){await adminApi.deleteBlogPost(p.id);load()}}}>Excluir</button></td></tr>)}</tbody></table></div></section>
}
